# Generated by Django 4.0.4 on 2022-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_delete_ahmet'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
