# Generated by Django 4.0.4 on 2022-04-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='reg_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
