# Generated by Django 4.0.4 on 2022-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_teachers_reg_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='reg_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
